services:
  redis:
    image: redis:4.0-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data

  postgres:
    image: postgres:10-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  judge:
    build:
      context: ./judge
      dockerfile: Dockerfile
    image: kimoo1/oj-judge:v1
    container_name: judge
    restart: unless-stopped
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/log:/log
      - ./data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://judge:8080
      - BACKEND_URL=http://backend:8000/api/judge_server_heartbeat/
      - TOKEN=CHANGE_THIS

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: kimoo1/oj-backend:v1
    container_name: backend
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
      - judge
    volumes:
      - ./data/backend:/data
      - ./backend:/app
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
      - JUDGE_SERVER_TOKEN=CHANGE_THIS
      - OJ_ENV=dev
    ports:
      - "8000:8000"

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: deploy/Dockerfile.dev
    container_name: frontend-dev
    depends_on:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - TARGET=http://backend:8000
    command: sh -c "npm run dev -- --host 0.0.0.0 --port 8080"
