# Generated by Django 4.2.20 on 2026-09-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    """출제자가 넣어 두는 정답 코드와 그 검증 결과."""


    dependencies = [
        ('problem', '0014_problem_archived_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solver_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='solver_language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='solver_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='solver_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='solver_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
